export default [
  //------Cold-----//
  {
    id: 1,
    name: "Combat Knife",
    price: "0.0001",
    weapon_type: "Cold",
    desc: "A combat knife is a fighting knife designed solely for military use and primarily intended for hand-to-hand or close combat fighting.",
    img: "/images/Guns/Cold/Combat-Knife.png",
  },
  {
    id: 2,
    name: "Dagger",
    price: "0.0002",
    weapon_type: "Cold",
    desc: "A dagger is a knife with a very sharp point and usually two sharp edges, typically designed or capable of being used as a thrusting or stabbing weapon.",
    img: '/images/Guns/Cold/Dagger.png',
  },
  {
    id: 3,
    name: "Pocket Knife",
    price: "0.0003",
    weapon_type: "Cold",
    desc: "A pocket knife is a knife with one or more blades that can be folded inwards to fit inside the knife handle.",
    img: "/images/Guns/Cold/Pocket-Knife.png",
  },
  {
    id: 4,
    name: "Warrior Knife",
    price: "0.0004",
    weapon_type: "Cold",
    desc: "The Warrior knife is a large curved blade fighting knife with a serrated back edge that was first made by Al Mar Knives and Round Eye Knife and Tool.",
    img: "/images/Guns/Cold/Warrior-Knife.png",
  },
  //------Pistol-----//
  {
    id: 5,
    name: "Beretta M9",
    price: "0.004",
    weapon_type: "Pistol",
    desc: "The M9 is a short recoil, semi-automatic, single-action / double-action pistol that uses a 15-round staggered box magazine with a reversible magazine release button that can be positioned for either right or left-handed shooters.",
    img: "/images/Guns/Pistol/Beretta.png",
  },
  {
    id: 6,
    name: "CZ-75",
    price: "0.007",
    weapon_type: "Pistol",
    desc: "The CZ 75 is a semi-automatic pistol made by Czech firearm manufacturer ČZUB. First introduced in 1975, it is one of the original \"wonder nines\" and features a staggered-column magazine, all-steel construction, and a hammer forged barrel.",
    img: "/images/Guns/Pistol/CZ75.png",
  },
  {
    id: 7,
    name: "Desert Eagle",
    price: "0.005",
    weapon_type: "Pistol",
    desc: "The Desert Eagle is a gas-operated, semi-automatic pistol known for chambering the . 50 Action Express, the largest centerfire cartridge of any magazine-fed, self-loading pistol. Magnum Research Inc.",
    img: "/images/Guns/Pistol/Desert-Eagle.png",
  },
  {
    id: 8,
    name: "FN-57",
    price: "0.002",
    weapon_type: "Pistol",
    desc: "The Five-seveN is a semi-automatic delayed blowback pistol chambered for FN's 5.7×28mm ammunition. The pistol has a concealed hammer. Polymer materials are used extensively in the pistol's design.",
    img: "/images/Guns/Pistol/FN5.png",
  },
  {
    id: 9,
    name: "Glock",
    price: "0.003",
    weapon_type: "Pistol",
    desc: "Glock is a brand of polymer-framed, short recoil-operated, locked-breech semi-automatic pistols designed and produced by Austrian manufacturer Glock Ges.m.b.H.",
    img: "/images/Guns/Pistol/Glock.png",
  },
  {
    id: 10,
    name: "HK-45",
    price: "0.0044",
    weapon_type: "Pistol",
    desc: "The Heckler & Koch HK45 (Heckler & Koch, .45 ACP) is a semi-automatic pistol designed by the German arms manufacturer Heckler & Koch.",
    img: "/images/Guns/Pistol/HK45.png",
  },
  {
    id: 11,
    name: "Jericho-941",
    price: "0.0095",
    weapon_type: "Pistol",
    desc: "The Jericho 941 is a double-action/single-action semi-automatic pistol developed by Israel Military Industries (now Israel Weapon Industries) introduced in 1990.",
    img: "/images/Guns/Pistol/Jericho-941.png",
  },
  {
    id: 12,
    name: "K-100",
    price: "0.0067",
    weapon_type: "Pistol",
    desc: "The K100 is a 9×19mm semi-automatic pistol designed and built by Grand Power s.r.o. in Slovenská Ľupča, Slovakia located approximately 11 kilometers east of Banská Bystrica, Slovakia which is the region's major city.",
    img: "/images/Guns/Pistol/K100.png",
  },
  {
    id: 13,
    name: "Makarov",
    price: "0.0012",
    weapon_type: "Pistol",
    desc: "The Makarov Pistol is a semi-automatic blowback action pistol. It is designed by Nikolay Makarov in 1948 and adopted by the Soviet Army in 1951.",
    img: "/images/Guns/Pistol/Makarov.png",
  },
  {
    id: 14,
    name: "P-227",
    price: "0.0032",
    weapon_type: "Pistol",
    desc: "The P227 is a double-action/single-action-operated handgun, meaning that the first trigger pull is a ten-lbs double-action pull, but all the follow-up shots are a 4.4-lbs single-action pull.",
    img: "/images/Guns/Pistol/P227.png",
  },
  {
    id: 15,
    name: "Remington-R1",
    price: "0.0046",
    weapon_type: "Pistol",
    desc: "The Remington 1911 R1 is a semi-automatic pistol modeled after the classic Colt 1911 which has served the US armed forces for over 100 years.",
    img: "/images/Guns/Pistol/Remington-R1.png",
  },
  {
    id: 16,
    name: "SW-1911",
    price: "0.0073",
    weapon_type: "Pistol",
    desc: "The SW1911 (Smith & Wesson) is a stainless steel framed, single action, semi-automatic pistol based on the M1911, coming in either 9×19mm or .45 ACP.",
    img: "/images/Guns/Pistol/SW1911.png",
  },
  //----Shotguns-----//
  {
    id: 17,
    name: "Benelli - M4",
    price: "0.013",
    weapon_type: "Shotgun",
    desc: "The Benelli M4 is a semi-automatic shotgun produced by Italian firearm manufacturer Benelli Armi SpA, and the last of the \"Benelli Super 90\" series of semi-automatic shotguns.",
    img: "/images/Guns/Shotgun/Benelli-M1014.png",
  },
  {
    id: 18,
    name: "KelTec KSG",
    price: "0.016",
    weapon_type: "Shotgun",
    desc: "The Kel-Tec KSG is a bullpup 12-gauge pump-action shotgun designed by Kel-Tec. It has two tube magazines which the user of the gun can switch between manually.",
    img: "/images/Guns/Shotgun/Kel-Tec-KSG.png",
  },
  {
    id: 19,
    name: "SPAS-12",
    price: "0.0178",
    weapon_type: "Shotgun",
    desc: "The Franchi SPAS-12 is a combat shotgun manufactured by Italian firearms company Franchi from 1979 to 2000. The SPAS-12 is a dual-mode shotgun, adjustable for semi-automatic or pump-action operation.",
    img: "/images/Guns/Shotgun/SPAS-12.png",
  },
  {
    id: 20,
    name: "Winchester-1200",
    price: "0.014",
    weapon_type: "Shotgun",
    desc: "The Model 1200 and Model 1300 are two pump-action shotguns that were manufactured by the Winchester-Western Division of Olin Corporation.",
    img: "/images/Guns/Shotgun/Winchester-Model-1200.png",
  },
  //---Light---//
  {
    id: 21,
    name: "CZ-Scorpion",
    price: "0.016",
    weapon_type: "Light",
    desc: "The Scorpion EVO 3 is a 9mm carbine manufactured by Česká zbrojovka Uherský Brod, the select-fire submachine gun variant is designated A1, and the semi-automatic variant is designated S1.",
    img: "/images/Guns/Light/CZ-Scorpion.png",
  },
  {
    id: 22,
    name: "Kriss Vector",
    price: "0.025",
    weapon_type: "Light",
    desc: "The KRISS Vector[4] is a series of weapons based upon the parent submachine gun design developed by the American company KRISS USA, formerly Transformational Defense Industries.",
    img: "/images/Guns/Light/KRISS-Vector.png",
  },
  {
    id: 23,
    name: "MP5",
    price: "0.0169",
    weapon_type: "Light",
    desc: "The MP5 is a 9x19mm Parabellum submachine gun, developed in the 1960s by a team of engineers from the German small arms manufacturer Heckler & Koch GmbH of Oberndorf am Neckar.",
    img: "/images/Guns/Light/MP5.png",
  },
  {
    id: 24,
    name:"MP7",
    price:"0.013",
    weapon_type:"Light",
    desc: "The MP7 is a personal defense weapon chambered for the HK 4.6×30mm armor-piercing cartridge designed by German defence manufacturer Heckler & Koch.",
    img:"/images/Guns/Light/MP7.png",
   
   },
   {
    id: 25,
    name:"P90",
    price:"0.034",
    weapon_type:"Light",
    desc: "The P90 is a selective fire, straight blowback-operated weapon with a cyclic rate of fire of around 850–1,100 rounds per minute. The weapon is chambered for FN's 5.7×28mm ammunition.",
    img:"/images/Guns/Light/P90.png",
   
   },
   {
    id: 26,
    name:"PPSH-41",
    price:"0.018",
    weapon_type:"Light",
    desc: "The PPSh-41 is a Soviet submachine gun designed by Georgy Shpagin as a cheap, reliable, and simplified alternative to the PPD-40",
    img:"/images/Guns/Light/PPSH-41.png",
   
   },
   {
    id: 27,
    name:"Thompson",
    price:"0.032",
    weapon_type:"Light",
    desc: "The Thompson submachine gun is a blowback-operated, air-cooled, magazine-fed selective-fire submachine gun, invented by the United States Army Brigadier general John T. Thompson in 1918.",
    img:"/images/Guns/Light/Thompson.png",
   
   },
   {
    id: 28,
    name:"Uzi",
    price:"0.04",
    weapon_type:"Light",
    desc: "The Uzi is a family of Israeli open-bolt, blowback-operated submachine guns and machine pistols first designed by Major Uziel \"Uzi\" Gal in the late 1940s, shortly after the establishment of the State of Israel.",
    img:"/images/Guns/Light/UZI.png",
   
   },
   //------Heavy------//
   {
    id: 29,
    name:"AK-12",
    price:"0.065",
    weapon_type:"Heavy",
    desc: "The AK-12 is a Russian assault rifle chambered in 5.45×39mm designed and manufactured by the Kalashnikov Concern (formerly Izhmash), making it the fifth generation of Kalashnikov rifles.",
    img:"/images/Guns/Heavy/AK12.png",
   
   },
   {
    id: 30,
    name:"AK-47",
    price:"0.075",
    weapon_type:"Heavy",
    desc: "he AK-47, officially known as the Avtomat Kalashnikov, is a gas-operated assault rifle that is chambered for the 7.62×39mm cartridge.",
    img:"/images/Guns/Heavy/AK47.png",
   
   },
   {
    id: 31,
    name:"AN-94",
    price:"0.032",
    weapon_type:"Heavy",
    desc: "The AN-94 is a Russian assault rifle. The initials stand for Avtomat Nikonova model of 1994, after its chief designer Gennadiy Nikonov, who previously worked on the Nikonov machine gun.",
    img:"/images/Guns/Heavy/AN-94.png",
   
   },
   {
    id: 32,
    name:"AUG A1",
    price:"0.045",
    weapon_type:"Heavy",
    desc: "The Steyr AUG is an Austrian bullpup assault rifle chambered for the 5.56×45mm NATO intermediate cartridge, designed in the 1960s by Steyr-Daimler-Puch, and now manufactured by Steyr Mannlicher GmbH & Co KG.",
    img:"/images/Guns/Heavy/AUG_A1.png",
   
   },
   {
    id: 33,
    name:"FN-F2000",
    price:"0.065",
    weapon_type:"Heavy",
    desc: "The FN F2000 is a 5.56×45mm NATO bullpup rifle, designed by FN Herstal in Belgium. The F2000 made its debut in March 2001 at the IDEX defence exhibition held in Abu Dhabi, in the United Arab Emirates.",
    img:"/images/Guns/Heavy/FN-F2000.png",
   
   },
   {
    id: 34,
    name:"FN-FAL",
    price:"0.025",
    weapon_type:"Heavy",
    desc: "The FAL is a battle rifle designed by Belgian small arms designer Dieudonné Saive and manufactured by FN Herstal (or simply known as FN).",
    img:"/images/Guns/Heavy/FN-FAL.png",
   
   },
   {
    id: 35,
    name:"FN-SCAR",
    price:"0.015",
    weapon_type:"Heavy",
    desc: "The FN SCAR (Special Operations Forces Combat Assault Rifle) is a family of gas-operated automatic rifles developed by Belgian manufacturer FN Herstal (FN) in 2004.",
    img:"/images/Guns/Heavy/FN-SCAR.png",
   
   },
   {
    id: 36,
    name:"Galil",
    price:"0.043",
    weapon_type:"Heavy",
    desc: "The IMI Galil is a family of Israeli-made automatic rifles chambered for the 5.56×45mm NATO or 7.62×51mm NATO cartridges. Originally designed by Yisrael Galili and Yakov Lior in the late 1960s.",
    img:"/images/Guns/Heavy/Galil.png",
   
   },
   {
    id: 37,
    name:"HK-G36",
    price:"0.019",
    weapon_type:"Heavy",
    desc: "The Heckler & Koch G36 is a 5.56×45mm assault rifle designed in the early 1990s by German company Heckler & Koch as a replacement for the heavier 7.62×51mm G3 battle rifle.",
    img:"/images/Guns/Heavy/HK-G36.png",
   
   },
   {
    id: 38,
    name:"KelTec RFB",
    price:"0.037",
    weapon_type:"Heavy",
    desc: "The Kel-Tec RFB (Rifle, Forward-ejection, Bullpup)[4] is a gas-operated bullpup weapon_type semi-automatic rifle, manufactured by Kel-Tec Industries of Florida.",
    img:"/images/Guns/Heavy/Kel-Tec-RFB.png",
   
   },
   {
    id: 39,
    name:"L85",
    price:"0.085",
    weapon_type:"Heavy",
    desc: "The SA80 is a British family of 5.56×45mm NATO service weapons used by the British Army. The L85 Rifle variant has been the standard issue service rifle of the British Armed Forces since 1987, replacing the L1A1 Self-Loading Rifle.",
    img:"/images/Guns/Heavy/L85.png",
   
   },
   {
    id: 40,
    name:"Carbine M1",
    price:"0.093",
    weapon_type:"Heavy",
    desc: "The M1 carbine is a lightweight semi-automatic carbine that was a standard firearm for the U.S. military during World War II, the Korean War and the Vietnam War.",
    img:"/images/Guns/Heavy/M1-Carbine.png",
   
   },
   {
    id: 41,
    name:"M4A1",
    price:"0.041",
    weapon_type:"Heavy",
    desc: "The M4A1 carbine is a fully automatic variant of the basic M4 carbine intended for special operations use. The M4A1 was introduced in May 1991 and was in service in 1994. The M4A1 was the first M4 model with the removable carry handle",
    img:"/images/Guns/Heavy/M4A1.png",
   
   },
   {
    id: 42,
    name:"M16",
    price:"0.016",
    weapon_type:"Heavy",
    desc: "The M16 rifle is a family of military rifles adapted from the ArmaLite AR-15 rifle for the United States military. The original M16 rifle was a 5.56×45mm automatic rifle with a 20-round magazine.",
    img:"/images/Guns/Heavy/M16.png",
   
   },
   {
    id: 43,
    name:"M249",
    price:"0.0249",
    weapon_type:"Heavy",
    desc: "The M249 light machine gun (LMG), also known as the M249 Squad Automatic Weapon (SAW), which continues to be the manufacturer's designation, and formally written as Light Machine Gun, 5.56 mm, M249.",
    img:"/images/Guns/Heavy/M249.png",
   
   },
   {
    id: 44,
    name:"STG-44",
    price:"0.044",
    weapon_type:"Heavy",
    desc: "The StG 44 is a German assault rifle developed during World War II by Hugo Schmeisser. It is also known by its early designations as the MP 43 and MP 44.",
    img:"/images/Guns/Heavy/STG44.png",
   
   },
   {
    id: 45,
    name:"X95",
    price:"0.095",
    weapon_type:"Heavy",
    desc: "The IWI X95 (formerly known as the Micro-Tavor, MTAR or MTAR-21) is an Israeli bullpup assault rifle designed and produced by Israel Weapon Industries (IWI) as part of the Tavor rifle family, along with the TAR-21 and the Tavor 7.",
    img:"/images/Guns/Heavy/X95.png",
   
   },
   {
    id: 46,
    name:"XM8",
    price:"0.08",
    weapon_type:"Heavy",
    desc: "The Heckler & Koch XM8 is a lightweight assault rifle system developed from the late 1990s to early 2000s. The rifle was designed by German small arms manufacturer Heckler & Koch, and shares design and engineering with their G36 rifle.",
    img:"/images/Guns/Heavy/XM8.png",
   },
   //-----Sniper-----/
   {
    id: 47,
    name:"AWP",
    price:"0.09",
    weapon_type:"Sniper",
    desc: "The Accuracy International Arctic Warfare rifle is a bolt-action sniper rifle designed and manufactured by the British company Accuracy International. It has proved popular as a civilian, police, and military rifle since its introduction in the 1980s.",
    img:"/images/Guns/Sniper/AWP.png",
   },
   {
    id: 48,
    name:"Dragunov SVD",
    price:"0.032",
    weapon_type:"Sniper",
    desc: "The Dragunov sniper rifle is a semi-automatic designated marksman rifle chambered in 7.62×54mmR and developed in the Soviet Union.",
    img:"/images/Guns/Sniper/Dragunov-SVD.png",
   },
   {
    id: 49,
    name:"DSR-1",
    price:"0.045",
    weapon_type:"Sniper",
    desc: "The DSR-1 is a compact bolt-action sniper rifle designed, manufactured and marketed by the German company DSR-Precision GmbH and was marketed also by the German company AMP Technical Services as a specialized sniper rifle for police sharpshooters.",
    img:"/images/Guns/Sniper/DSR-1.png",
   },
   {
    id: 50,
    name:"M24",
    price:"0.026",
    weapon_type:"Sniper",
    desc: "The M24 is the military and police version of the Remington Model 700 rifle, M24 being the model name assigned by the United States Army after adoption as their standard sniper rifle in 1988.",
    img:"/images/Guns/Sniper/M24.png",
   },
   {
    id: 51,
    name:"SV-98",
    price:"0.038",
    weapon_type:"Sniper",
    desc: "The SV-98 is a Russian bolt-action sniper rifle designed by Vladimir Stronskiy. In 2003 special operations troops were armed with the 7.62 mm 6S11 sniper system comprising the SV-98 sniper rifle and 7N14 sniper enhanced penetration round.",
    img:"/images/Guns/Sniper/SV-98.png",
   },
   {
    id: 52,
    name:"M95",
    price:"0.1",
    weapon_type:"Sniper",
    desc: "The Barrett M95 is a bolt-action rifle chambered in .50 BMG (12.7×99mm), and manufactured by Barrett Firearms Company. It has been adopted by a number of militaries around the world.",
    img:"/images/Guns/Sniper/M95.png",
   }

];
